// (C) 2013 Sebastian Mach (1983), this file is published under the terms of the
// GNU General Public License, Version 3 (a.k.a. GPLv3).
// See COPYING in the root-folder of the excygen project folder.

#include "raytrace.hh"
#include "Photometry/Lighting.hh"
#include "Primitives/PrimitiveList.hh"
#include "SurfaceIntegrators/Path.hh"
#include "ImageFormat/PPM.hh"

#include <Python.h>
#include <boost/python.hpp>

#include <iostream>

namespace PyAPI {
    std::string api_version()
    {
        return "<master>";
    }

    std::string api_compile_date()
    {
        return __DATE__;
    }


    struct Renderer {
        int width, height, samples_per_pixel;

        Renderer(int width, int height, int samples_per_pixel) :
            width(width), height(height), samples_per_pixel(samples_per_pixel) {}
    };

    struct SurfaceIntegrator {
        int maximum_recursion = 5;

        SurfaceIntegrator() {}
    };


    void render(Renderer const &renderer) {
        using namespace excyrender;

        SurfaceIntegrator surface_integrator;

        std::clog << "rendering (" << renderer.width << "x" << renderer.height << "@"
                  << renderer.samples_per_pixel << "spp)" << std::endl;

        std::vector<Photometry::RGB> pixels(renderer.width*renderer.height);
        std::vector<DebugPixel> debug(renderer.width*renderer.height);

        std::vector<std::shared_ptr<Photometry::LightSource>> const lightSources({
            std::shared_ptr<Photometry::LightSource>(new Photometry::Directional (
                  Geometry::direction(1,0.5,-1),
                  Photometry::Spectrum::FromRGB(400,800,8,{10,10,10}))
            )
        });

        Primitives::PrimitiveList const primitive({});

        auto const integrator =
                SurfaceIntegrators::Path(
                    surface_integrator.maximum_recursion,
                    primitive,
                    lightSources,
                    [](Geometry::Direction const &) {
                        return Photometry::Spectrum::FromRGB(400,800,8,{1,2,3});
                    }
                );

        raytrace (renderer.width, renderer.height, renderer.samples_per_pixel,
                  integrator, pixels, debug);

        ImageFormat::ppm (std::cout,
                          renderer.width, renderer.height, pixels);
    }
}



BOOST_PYTHON_MODULE(excygen) {
    using namespace boost::python;
    using namespace PyAPI;
    def("api_version", api_version);
    def("api_compile_date", api_compile_date);

    def("render", render, (arg("renderer")));

    class_<Renderer>("Renderer", init<int, int, int>((arg("width")=640, arg("height")=480, arg("sample_per_pixel")=16)))
      .def_readonly("width", &Renderer::width)
      .def_readonly("height", &Renderer::height)
      .def_readonly("samples_per_pixel", &Renderer::samples_per_pixel);
}



void PythonAPI(std::string const &script)
{
    std::clog << "excygen python api" << std::endl;
    //Py_SetProgramName(argv[0]);

    std::clog << "initialize python environment..." << std::endl;
    Py_Initialize();

    std::clog << "importing excygen API into python environment..." << std::endl;
    initexcygen(); // This function is generated by BOOST_PYTHON_MODULE and
                   // enriches the Python runtime environment with our API.

    try {
        using namespace boost::python;
        object main_module = import("__main__");
        object main_namespace = main_module.attr("__dict__");

        std::clog << "-- running script ----------------------------------------" << std::endl;
        exec(script.c_str(),
             main_namespace);
        std::clog << "----------------------------------------------------------" << std::endl;
    } catch (boost::python::error_already_set const &) {
        PyErr_Print();
    }

    std::clog << "finalizing..." << std::endl;
    Py_Finalize();

    std::clog << "hope you are happy!" << std::endl;
}
