#include <Python.h>
#include <boost/python.hpp>
#include <iostream>

namespace PyAPI {
    std::string api_version()
    {
        return "<master>";
    }

    std::string api_compile_date()
    {
        return __DATE__;
    }
}



BOOST_PYTHON_MODULE(excygen) {
    using namespace boost::python;
    def("api_version", PyAPI::api_version);
    def("api_compile_date", PyAPI::api_compile_date);
}

int PythonAPI(int argc, char *argv[])
{
    Py_SetProgramName(argv[0]);
    Py_Initialize();
    initexcygen(); // This function is generated by BOOST_PYTHON_MODULE and
                   // enriches the Python runtime environment with our API.

    try {
        using namespace boost::python;
        object main_module = import("__main__");
        object main_namespace = main_module.attr("__dict__");

        exec("import excygen\n"
             "print 'excygen version: {0}'.format(excygen.api_version())\n"
             "print 'API compiled at {0}'.format(excygen.api_compile_date())\n",
             main_namespace);
    } catch (boost::python::error_already_set const &) {
        PyErr_Print();
    }

    Py_Finalize();
    return 0;
}
