env = Environment(CPPPATH = ['.'],
                  CXXFLAGS="-std=c++0x -O3"
                  )

env.Program(['main.cc',
             'ImageFormat/PPM.cc',
             'Photometry/SPD/Regular.cc',
             'Photometry/SPD/Constant.cc',
             'Photometry/Spectrum.cc',
             ])
