env = Environment(CPPPATH = ['.'],
                  CXXFLAGS="-std=c++0x -Wall -O3 -ffast-math -march=native -msse2 -fopenmp",
                  )

t = env.Program(target='excygen',
                source=['main.cc',
                        'ImageFormat/PPM.cc',
                        'Photometry/SPD/Regular.cc',
                        'Photometry/SPD/Constant.cc',
                        'Photometry/Spectrum.cc',
                        'Primitives/BoundingIntervalHierarchy.cc',
                        'Shapes/BoundingIntervalHierarchy.cc',
                        'DebugPixel.cc',
                        'Shapes/Terrain2d.cc',
                        'Scripting/Et1.cc',
                        'Scripting/Et1/Token.cc',
                        'Scripting/Et1/AST.cc',
                        'Scripting/Et1/transform/lambda_lift.cc'
                       ],
                       LIBS=['gomp', 'SDL', 'SDL_image']
               )
Default(t)
